/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ContractScript } from "./ContractScript";
export type { INativeSender } from "./INativeSender";
export type { IWormholeAndNativeSender } from "./IWormholeAndNativeSender";
