import fs from "fs/promises";
import { DEPLOYMENTS } from "./deployments";
const FILE_NAME = "./src/utils/deployments.ts";
const ENCODING = "utf-8";
export default async function updateDeployments(
  key: string,
  eth: string,
  opt: string
) {
  (DEPLOYMENTS as any)[key] = {
    eth,
    opt,
  };
  await fs.writeFile(
    FILE_NAME,
    `/* Autogenerated file. Do not edit manually. */
export const DEPLOYMENTS = ${JSON.stringify(DEPLOYMENTS, undefined, 2)};
`,
    ENCODING
  );
}
