/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace Messages {
  export type UpdateMessageStruct = {
    payloadID: PromiseOrValue<BigNumberish>;
    message: PromiseOrValue<string>;
  };

  export type UpdateMessageStructOutput = [number, string] & {
    payloadID: number;
    message: string;
  };
}

export interface NativeReceiverInterface extends utils.Interface {
  functions: {
    "decodeMessage(bytes)": FunctionFragment;
    "encodeMessage((uint8,string))": FunctionFragment;
    "expectPayload(bytes32)": FunctionFragment;
    "expectedPayloadHash()": FunctionFragment;
    "l1SenderAddress()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "decodeMessage"
      | "encodeMessage"
      | "expectPayload"
      | "expectedPayloadHash"
      | "l1SenderAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "decodeMessage",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "encodeMessage",
    values: [Messages.UpdateMessageStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "expectPayload",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "expectedPayloadHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "l1SenderAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "decodeMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encodeMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expectPayload",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expectedPayloadHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l1SenderAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface NativeReceiver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NativeReceiverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    decodeMessage(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [Messages.UpdateMessageStructOutput] & {
        parsedMessage: Messages.UpdateMessageStructOutput;
      }
    >;

    encodeMessage(
      parsedMessage: Messages.UpdateMessageStruct,
      overrides?: CallOverrides
    ): Promise<[string] & { encodedMessage: string }>;

    expectPayload(
      _expectedPayloadHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    expectedPayloadHash(overrides?: CallOverrides): Promise<[string]>;

    l1SenderAddress(overrides?: CallOverrides): Promise<[string]>;
  };

  decodeMessage(
    encodedMessage: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<Messages.UpdateMessageStructOutput>;

  encodeMessage(
    parsedMessage: Messages.UpdateMessageStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  expectPayload(
    _expectedPayloadHash: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  expectedPayloadHash(overrides?: CallOverrides): Promise<string>;

  l1SenderAddress(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    decodeMessage(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<Messages.UpdateMessageStructOutput>;

    encodeMessage(
      parsedMessage: Messages.UpdateMessageStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    expectPayload(
      _expectedPayloadHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    expectedPayloadHash(overrides?: CallOverrides): Promise<string>;

    l1SenderAddress(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    decodeMessage(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    encodeMessage(
      parsedMessage: Messages.UpdateMessageStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    expectPayload(
      _expectedPayloadHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    expectedPayloadHash(overrides?: CallOverrides): Promise<BigNumber>;

    l1SenderAddress(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    decodeMessage(
      encodedMessage: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    encodeMessage(
      parsedMessage: Messages.UpdateMessageStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    expectPayload(
      _expectedPayloadHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    expectedPayloadHash(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    l1SenderAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
