/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  INativeSender,
  INativeSenderInterface,
} from "../../register_receiver.sol/INativeSender";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_receiverL2Addr",
        type: "address",
      },
    ],
    name: "nativeBridgeSetup",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INativeSender__factory {
  static readonly abi = _abi;
  static createInterface(): INativeSenderInterface {
    return new utils.Interface(_abi) as INativeSenderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INativeSender {
    return new Contract(address, _abi, signerOrProvider) as INativeSender;
  }
}
