/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWormholeAndNativeSender,
  IWormholeAndNativeSenderInterface,
} from "../../register_receiver.sol/IWormholeAndNativeSender";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_receiverL2Addr",
        type: "address",
      },
    ],
    name: "nativeBridgeSetup",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWormholeAndNativeSender__factory {
  static readonly abi = _abi;
  static createInterface(): IWormholeAndNativeSenderInterface {
    return new utils.Interface(_abi) as IWormholeAndNativeSenderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWormholeAndNativeSender {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IWormholeAndNativeSender;
  }
}
